sudo: required

language: perl6

os:
  - linux
  - osx

perl6:
  - 2016.12
  - latest

install:
  - echo $TRAVIS_OS_NAME
  - rakudobrew build zef
  - zef --depsonly install .
  - zef install Test::META
  - zef build .

before_script:
  # Start xvfb for Firefox headless testing and give it some time to start
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then export DISPLAY=:99.0         ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sh -e /etc/init.d/xvfb start ; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sleep 3                      ; fi
  # Install PhantomJS on MacOSX using homebrew
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew update                  ; fi
  - if [ "$TRAVIS_OS_NAME" == "osx"   ]; then brew install phantomjs       ; fi
  # Show PhantomJS version
  - phantomjs --version

script:
    - prove -ve "perl6 -Ilib" t
    - TEST_AUTHOR=1 prove -ve "perl6 -Ilib" t
    - zef install Selenium::WebDriver
